services:
  bboplace:
    container_name: agentbbo_bboplace
    image: gaozhixuan/bboplace-bench
    ports:
      - "8070:8080"

  dbtune-mariadb:
    container_name: agentbbo_http_mariadb_eval
    build:
      context: ./bbo/tasks/dbtune/docker_mariadb
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  dbtune-surrogate:
    container_name: agentbbo_surrogate_http
    build:
      context: ./bbo/tasks/dbtune
      dockerfile: docker_surrogate/Dockerfile
    ports:
      - "8090:8090"
    volumes:
      - ./bbo/tasks/dbtune/assets:/app/assets:ro
